name: Deploy Policy Builder to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-push-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: '1'
          submodules: 'recursive'
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install packages
        run: npm ci
      - name: Build dashboard library
        run: npm run lib-build -- --configuration production
      - name: Build policy builder app
        run: npm run build -- --configuration production
      - name: Push to gh-pages branch
        run: |
            git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
            npx --package=gh-pages@6.3.0 gh-pages -u "github-actions-bot <support+actions@github.com>" --dist dist/data-dashboard/browser --dest policy-builder/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
